### ISSUE TITLE
learn more git

### ISSUE THREAD

**Issue by bearzk** [Panda-Bear-Studio/Games-Gallery#5]
- pull
- merge
- rebase

**Comment by MiaoziYu** [comment]
大熊！可是我不会呀！

**Comment by MiaoziYu** [comment]
大熊，你可不可以教我呢

**Comment by bearzk** [comment]
sure thing, let’s do this tomorrow, together :)

**Comment by bearzk** [comment]
I think we can close this one since you are familiar with all these already :+1:
